version: '3'
services:
  mysql-docker:
    image: mysql:latest
    container_name: mysql-docker
    networks:
      - my-network
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  app:
    image: akaushal85/spring-boot-docker:latest
    container_name: spring-boot-app
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - mysql-docker
networks:
  my-network:
    driver: bridge
    